name: Unit and e2e tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pre-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Angular dependencies
        run: npm install

  unit-tests:
    needs: pre-install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run unit tests
        run: npm run test

  e2e-tests:
    needs: [pre-install, unit-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start development server
        run: ng serve --port 4200

      - name: Run e2e tests
        run: npm run cypress:open
