name: Unit and e2e tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pre-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: pre-install
          if-no-files-found: error
          path: pre-install

  build:
    needs: pre-install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: pre-install
          path: pre-install
      - name: Build
        run: npm run build

  lint:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: pre-install
          path: pre-install
      - name: Run lint
        run: npm run lint:ci

  unit-tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: pre-install
          path: pre-install
      - name: Run unit tests
        run: npm run test:ci

  e2e-tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: npm run build
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start:ci
          browser: chrome
